<?php
// Stable keys: do not regenerate this catalog when defaults change.
return [
    'deck_label' => ['group' => 'Galería premium · Estilo Baraja', 'default' => 'Galería de fotografías en baraja'],
    'drum_label' => ['group' => 'Galería premium · Estilo Tambor', 'default' => 'Galería de fotografías en tambor'],
    'cylinder_label' => ['group' => 'Galería premium · Estilo Cilindro', 'default' => 'Galería de fotografías en cilindro'],
    'polaroid_label' => ['group' => 'Galería premium · Estilo Polaroids', 'default' => 'Galería de fotografías en polaroids'],
    'swipe_label' => ['group' => 'Galería premium · Estilo Tinder', 'default' => 'Galería de fotografías para deslizar'],
    'swipe_like_label' => ['group' => 'Galería premium · Estilo Tinder', 'default' => 'Dar un corazón a la foto y pasar a la siguiente'],
    'swipe_pass_label' => ['group' => 'Galería premium · Estilo Tinder', 'default' => 'Pasar a la siguiente foto'],
    'swipe_hint_touch' => ['group' => 'Galería premium · Estilo Tinder', 'default' => 'Desliza → ♥ corazón · ← siguiente'],
    'swipe_hint_wheel' => ['group' => 'Galería premium · Estilo Tinder', 'default' => 'Arrastra o usa las flechas: → ♥ corazón · ← siguiente'],
    'swipe_end' => ['group' => 'Galería premium · Estilo Tinder', 'default' => 'Has visto todas las fotos'],
    'swipe_restart' => ['group' => 'Galería premium · Estilo Tinder', 'default' => 'Volver a empezar'],
    'deck_prev' => ['group' => 'Galería premium · Estilo Baraja', 'default' => 'Foto anterior'],
    'deck_next' => ['group' => 'Galería premium · Estilo Baraja', 'default' => 'Foto siguiente'],
    'deck_hint_touch' => ['group' => 'Galería premium · Estilo Baraja', 'default' => 'Desliza hacia arriba'],
    'deck_hint_wheel' => ['group' => 'Galería premium · Estilo Baraja', 'default' => 'Rueda del ratón o flechas'],
    'deck_exit' => ['group' => 'Galería premium · Estilo Baraja', 'default' => 'Salir'],
    'deck_exit_label' => ['group' => 'Galería premium · Estilo Baraja', 'default' => 'Salir de la galería y seguir viendo la web'],
    'deck_exit_up_label' => ['group' => 'Galería premium · Estilo Baraja', 'default' => 'Salir de la galería hacia arriba'],
    'deck_empty_filter' => ['group' => 'Galería premium · Estilo Baraja', 'default' => 'No hay fotos en esta selección'],
    'bubbles_label' => ['group' => 'Galería premium · Estilo Burbujas', 'default' => 'Galería de fotografías en burbujas'],
    'squares_label' => ['group' => 'Galería premium · Estilo Cuadrados', 'default' => 'Galería de fotografías en cuadrados'],
    'bubbles_prev' => ['group' => 'Galería premium · Estilo Burbujas', 'default' => 'Página anterior'],
    'bubbles_next' => ['group' => 'Galería premium · Estilo Burbujas', 'default' => 'Página siguiente'],
    'bubbles_hint_touch' => ['group' => 'Galería premium · Estilo Burbujas', 'default' => 'Desliza hacia arriba · pulsa una foto'],
    'bubbles_hint_wheel' => ['group' => 'Galería premium · Estilo Burbujas', 'default' => 'Rueda del ratón o flechas · pulsa una foto'],
    'bubbles_empty_filter' => ['group' => 'Galería premium · Estilo Burbujas', 'default' => 'No hay fotos en esta selección'],
    'categories_title' => ['group' => 'Inicio y galería', 'default' => 'Categorías'],
    'photo_navigation' => ['group' => 'Controles e instalación', 'default' => 'Navegación entre fotografías'],
    'social_threads_user' => ['group' => 'Perfil y redes', 'default' => '@kookyecatgallery'],
    'text_52179dc42df7efe5' => ['group' => 'Inicio y galería · accesibilidad', 'default' => 'Kookye Cat Gallery'],
    'text_2c6b326536186079' => ['group' => 'Inicio y galería', 'default' => 'Kookye Cat Gallery'],
    'text_20ab386d12d982bd' => ['group' => 'Inicio y galería', 'default' => 'Ver'],
    'text_929d5afb3be64e4a' => ['group' => 'Inicio y galería · accesibilidad', 'default' => 'Subir una fotografía'],
    'text_c55b46a0c60668c4' => ['group' => 'Inicio y galería', 'default' => 'Añadir foto'],
    'text_f99ccb8765ac6c3a' => ['group' => 'Inicio y galería', 'default' => 'Volver a la galería'],
    'text_e7d9334b34fa5f57' => ['group' => 'Inicio y galería · accesibilidad', 'default' => 'Ampliar fotografía a pantalla completa'],
    'text_5ebed0b0766b91d4' => ['group' => 'Inicio y galería', 'default' => 'Solo foto'],
    'text_d020a22b29eaad92' => ['group' => 'Inicio y galería', 'default' => 'Ver a pantalla completa'],
    'text_2f620d60184d9043' => ['group' => 'Inicio y galería', 'default' => 'Editar fotografía'],
    'text_c9a6bc6eb8882183' => ['group' => 'Inicio y galería · accesibilidad', 'default' => 'Fotografías relacionadas'],
    'text_cfed0e3af4509ead' => ['group' => 'Inicio y galería', 'default' => 'Sigue explorando'],
    'text_90dd4cd34311daa0' => ['group' => 'Inicio y galería', 'default' => 'Más de'],
    'text_83f4e59e2da59d76' => ['group' => 'Inicio y galería · accesibilidad', 'default' => 'Inicio · Kookye Cat Gallery'],
    'text_b6b50664e231e202' => ['group' => 'Inicio y galería', 'default' => 'Galería fotográfica y portfolio de autor.'],
    'text_cbbba360eb60dd04' => ['group' => 'Inicio y galería', 'default' => 'Fotos'],
    'text_2c1ac3057629f681' => ['group' => 'Inicio y galería', 'default' => 'de autor'],
    'text_30170303c506cf6c' => ['group' => 'Inicio y galería', 'default' => 'Kookye Cat Gallery'],
    'text_08e81d4e64f6b4ff' => ['group' => 'Inicio y galería', 'default' => 'fotografía'],
    'text_eefccddb211b22ea' => ['group' => 'Inicio y galería', 'default' => 'Sube fotografías por FTP a'],
    'text_7fe0e410821a1ee4' => ['group' => 'Inicio y galería', 'default' => '/img/'],
    'text_cc0ecea94d78a73f' => ['group' => 'Inicio y galería', 'default' => 'y aparecerán aquí automáticamente.'],
    'text_ddfe959388cbea71' => ['group' => 'Inicio y galería · accesibilidad', 'default' => 'Ir a la galería'],
    'text_b2cec4172b3ff4d2' => ['group' => 'Inicio y galería', 'default' => 'Explorar archivo'],
    'text_1d997c72b89b5e1f' => ['group' => 'Inicio y galería · accesibilidad', 'default' => 'Perfil de Kookye Cat Gallery'],
    'text_84f085942c2a2aa1' => ['group' => 'Inicio y galería · accesibilidad', 'default' => 'Ir al inicio · Kookye Cat Gallery'],
    'text_8aa8595771f39463' => ['group' => 'Inicio y galería', 'default' => 'Diario visual de autor'],
    'text_125ff372f2933b34' => ['group' => 'Inicio y galería · accesibilidad', 'default' => 'Logotipo de la galería'],
    'text_7f9488ff977b7f67' => ['group' => 'Inicio y galería · accesibilidad', 'default' => 'Estadísticas de la galería'],
    'text_577e559428a23438' => ['group' => 'Inicio y galería', 'default' => 'fotografías'],
    'text_bb6db5ced87f3dfa' => ['group' => 'Inicio y galería', 'default' => 'miradas'],
    'text_b5c772cf5b14f84e' => ['group' => 'Inicio y galería', 'default' => 'Fotografías'],
    'text_ff1de97302308752' => ['group' => 'Inicio y galería', 'default' => 'mi tierra'],
    'text_4577bab0d9627af1' => ['group' => 'Inicio y galería', 'default' => '@KookyeCatGallery'],
    'text_6ba397681d3ee9c1' => ['group' => 'Inicio y galería · accesibilidad', 'default' => 'Perfil verificado'],
    'text_2e2b80d871481edc' => ['group' => 'Inicio y galería', 'default' => 'Fotografía de autor, historias visuales y pequeños detalles.'],
    'text_54b7645201863e32' => ['group' => 'Inicio y galería', 'default' => 'Una colección de imágenes y proyectos fotográficos.'],
    'text_e5d843682b4f2596' => ['group' => 'Inicio y galería · accesibilidad', 'default' => 'Visitar example.com, se abre en una pestaña nueva'],
    'text_7e6debbd1dab03b1' => ['group' => 'Inicio y galería', 'default' => 'example.com'],
    'text_aff4d19d6ee43b20' => ['group' => 'Inicio y galería', 'default' => 'Todas'],
    'text_7d367bc92702d135' => ['group' => 'Inicio y galería', 'default' => 'Fotografías, momentos y pequeños detalles'],
    'text_c15e876671f50d92' => ['group' => 'Inicio y galería', 'default' => 'Fotografías de'],
    'text_a9157ae01488ec67' => ['group' => 'Inicio y galería', 'default' => ' y sus miradas curiosas, juegos y aventuras cotidianas. Explora la colección y abre cualquier imagen para verla a pantalla completa.'],
    'text_5935e29992445803' => ['group' => 'Inicio y galería · accesibilidad', 'default' => 'Navegación de páginas'],
    'text_d50e1dd2fb1b8143' => ['group' => 'Inicio y galería', 'default' => 'Explora la galería'],
    'text_525b8adbcb4f9654' => ['group' => 'Inicio y galería', 'default' => 'Lugares de las fotografías'],
    'text_b22780340ae5569f' => ['group' => 'Inicio y galería', 'default' => 'Explorar por categoría'],
    'text_68b4717007382b83' => ['group' => 'Inicio y galería · accesibilidad', 'default' => 'Filtrar fotografías por categoría'],
    'text_425a839def0b84fd' => ['group' => 'Inicio y galería', 'default' => 'Todas las categorías'],
    'text_ee497220c8c386d8' => ['group' => 'Inicio y galería · accesibilidad', 'default' => 'Imagen de perfil de Kookye Cat Gallery'],
    'text_c9248cc61aa75376' => ['group' => 'Inicio y galería', 'default' => 'El proyecto'],
    'text_6636c29ab23b6ec8' => ['group' => 'Inicio y galería', 'default' => 'Mirar el mundo despacio'],
    'text_3d9d76375e115725' => ['group' => 'Inicio y galería', 'default' => 'despacio'],
    'text_9b9e0ce956198ed6' => ['group' => 'Inicio y galería', 'default' => 'es una colección fotográfica en crecimiento, dedicada a una mirada personal y a los momentos que merece la pena recordar.'],
    'text_ded2b00dd9f9aee9' => ['group' => 'Inicio y galería', 'default' => 'Cada imagen captura una mirada de'],
    'text_5b20d476495c8ab2' => ['group' => 'Inicio y galería', 'default' => '.
                    Retratos, paisajes y escenas cotidianas.
                    Una colección visual para disfrutar sin prisa.'],
    'text_92d07ee88e566b66' => ['group' => 'Inicio y galería', 'default' => 'Ver la colección'],
    'text_f0430f9bb09ea2c6' => ['group' => 'Inicio y galería · accesibilidad', 'default' => 'Visor de fotografía'],
    'text_69dd3ff6fd21ed0e' => ['group' => 'Inicio y galería · accesibilidad', 'default' => 'Ver solo la fotografía a pantalla completa'],
    'text_aae4e10e8be39bd5' => ['group' => 'Inicio y galería · accesibilidad', 'default' => 'Ver solo la fotografía'],
    'text_2b26671eb88810be' => ['group' => 'Inicio y galería · accesibilidad', 'default' => 'Cerrar imagen'],
    'text_6e24ef52e0e9edbd' => ['group' => 'Inicio y galería · accesibilidad', 'default' => 'Foto anterior'],
    'text_8bed218e5d1a26ca' => ['group' => 'Inicio y galería · accesibilidad', 'default' => 'Foto siguiente'],
    'text_e06e2e6400797b86' => ['group' => 'Inicio y galería · accesibilidad', 'default' => 'Volver arriba'],
    'text_bdd8f61b94c52379' => ['group' => 'Inicio y galería', 'default' => 'Hablemos'],
    'text_49a006d539216e16' => ['group' => 'Inicio y galería', 'default' => '¿Una copia, un encargo'],
    'text_f366ccf006a44b3f' => ['group' => 'Inicio y galería', 'default' => 'o simplemente saludar?'],
    'text_ab3ceef210237f9d' => ['group' => 'Inicio y galería', 'default' => 'Sígueme y escríbeme por mensaje directo. Estoy en:'],
    'text_bad57ef7837c8e6b' => ['group' => 'Inicio y galería', 'default' => 'Instagram'],
    'text_3b20084d3d94b4ee' => ['group' => 'Inicio y galería', 'default' => '@kookyecatgallery'],
    'text_3e42e385075b9b56' => ['group' => 'Inicio y galería', 'default' => 'Threads'],
    'text_318bb1fc64a6e036' => ['group' => 'Inicio y galería', 'default' => 'Kookye Cat Gallery'],
    'text_7664bd753da07ad5' => ['group' => 'Inicio y galería', 'default' => 'Aviso Legal'],
    'text_52233e2c4d6b2e9a' => ['group' => 'Inicio y galería', 'default' => 'Privacidad'],
    'text_141395eb35564fe5' => ['group' => 'Inicio y galería', 'default' => 'Cookies'],
    'text_1a1b3e6ecc51b478' => ['group' => 'Inicio y galería', 'default' => 'Administración'],
    'text_f1e02d469cf54d61' => ['group' => 'Inicio y galería', 'default' => 'Instalar app'],
    'text_400a7f33d431611c' => ['group' => 'Identidad, metadatos y controles', 'default' => 'Fotografía de autor'],
    'text_1a0ef9e63d20942b' => ['group' => 'Identidad, metadatos y controles', 'default' => 'Kookye Cat Gallery · Fotografía de autor'],
    'text_506b817f8bd1888e' => ['group' => 'Identidad, metadatos y controles', 'default' => 'Una colección de fotografía de autor: imágenes, proyectos e historias visuales. {count} imágenes.'],
    'text_570bd4204e3d077b' => ['group' => 'Identidad, metadatos y controles', 'default' => 'fotografía, portfolio, galería fotográfica, fotografía de autor, proyectos fotográficos'],
    'text_3906c387259fafc4' => ['group' => 'Aviso legal · accesibilidad', 'default' => 'Volver al inicio'],
    'text_ab26ae7bca362195' => ['group' => 'Aviso legal', 'default' => 'Volver'],
    'text_062798b6730bc603' => ['group' => 'Aviso legal', 'default' => '1. Datos del titular'],
    'text_3ab8939d4e00a5af' => ['group' => 'Aviso legal', 'default' => 'El presente sitio web'],
    'text_27e9006e3ef330f5' => ['group' => 'Aviso legal', 'default' => 'example.com'],
    'text_3efdbafd42b5d980' => ['group' => 'Aviso legal', 'default' => 'es titularidad de'],
    'text_a6b54c20a7b96eea' => ['group' => 'Aviso legal', 'default' => 'Responsable de la galería'],
    'text_a18558f9e518a164' => ['group' => 'Aviso legal', 'default' => '; domicilio: [completar antes de publicar]'],
    'text_8d33d070d6c4b081' => ['group' => 'Aviso legal', 'default' => '[completar jurisdicción antes de publicar]'],
    'text_2187148fa660c266' => ['group' => 'Aviso legal', 'default' => '2. Objeto'],
    'text_f2ee3e3d50ad633a' => ['group' => 'Aviso legal', 'default' => 'Este sitio presenta fotografías. Revisa y adapta este texto legal de ejemplo antes de publicar la instalación.'],
    'text_f8f93bd27ed1978b' => ['group' => 'Aviso legal', 'default' => '3. Condiciones de uso'],
    'text_6f2df8fcd7adb09a' => ['group' => 'Aviso legal', 'default' => 'El usuario se compromete a hacer un uso adecuado del sitio web y de sus contenidos, sin emplearlos para realizar actividades ilícitas o contrarias a la buena fe y al ordenamiento jurídico.'],
    'text_e569619cdbd969d7' => ['group' => 'Aviso legal', 'default' => 'Queda prohibido el uso del sitio con fines comerciales sin autorización expresa del titular.'],
    'text_700391b16151dc07' => ['group' => 'Aviso legal', 'default' => '4. Propiedad intelectual'],
    'text_dfb5ef92b4e378f2' => ['group' => 'Aviso legal', 'default' => 'Este contenido y las fotografías deben adaptarse a los derechos de uso y titularidad de cada instalación antes de publicar.'],
    'text_f246188b9c948197' => ['group' => 'Aviso legal', 'default' => 'Queda expresamente prohibida la reproducción, distribución, comunicación pública, transformación o cualquier otra explotación de los contenidos sin autorización previa y por escrito del titular.'],
    'text_a281cb39d20c3b93' => ['group' => 'Aviso legal', 'default' => '5. Responsabilidad'],
    'text_afa8e64bd135ce59' => ['group' => 'Aviso legal', 'default' => 'El titular no se hace responsable de los daños y perjuicios que pudieran derivarse de interferencias, omisiones, interrupciones, virus informáticos, averías telefónicas o desconexiones en el funcionamiento operativo del sistema electrónico, motivadas por causas ajenas a su control.'],
    'text_c1034cc37bc846be' => ['group' => 'Aviso legal', 'default' => '6. Legislación aplicable'],
    'text_381a9a6057d20dd5' => ['group' => 'Aviso legal', 'default' => 'Completa este apartado con la legislación y jurisdicción que correspondan a tu instalación.'],
    'text_7e9d4894ce5d22db' => ['group' => 'Aviso legal', 'default' => '7. Modificaciones'],
    'text_e008dedd60aef2cc' => ['group' => 'Aviso legal', 'default' => 'El titular se reserva el derecho a modificar el contenido del presente aviso legal en cualquier momento sin previo aviso.'],
    'text_57bdd4e7e9940c57' => ['group' => 'Aviso legal', 'default' => 'Kookye Cat Gallery'],
    'text_6af46c1fff648aa4' => ['group' => 'Identidad, metadatos y controles', 'default' => 'Aviso Legal · Kookye Cat Gallery'],
    'text_f40a08d55695b46c' => ['group' => 'Privacidad', 'default' => '1. Data controller'],
    'text_cf1af996c0acd526' => ['group' => 'Privacidad', 'default' => 'Identifica al responsable del tratamiento y sus datos de contacto antes de publicar.'],
    'text_676a588f80001416' => ['group' => 'Privacidad', 'default' => ', titular del sitio web'],
    'text_3641805d702325c1' => ['group' => 'Privacidad', 'default' => '2. Datos que se recogen'],
    'text_bf0616b7f3cfa510' => ['group' => 'Privacidad', 'default' => 'Este sitio web es una galería fotográfica de exhibición pública. No dispone de formularios de registro, contacto, comentarios, suscripción ni ningún otro mecanismo que recopile datos personales de los usuarios.'],
    'text_de7d8a234348e034' => ['group' => 'Privacidad', 'default' => 'Los únicos datos que pudieran procesarse son los datos técnicos de navegación habituales (dirección IP, navegador, sistema operativo) que el servidor web registra de forma automática con fines de seguridad y diagnóstico, sin asociarlos a ningún usuario identificable.'],
    'text_aa852d396fdca6d6' => ['group' => 'Privacidad', 'default' => '3. Finalidad y base legal'],
    'text_398edb1b02bac0a3' => ['group' => 'Privacidad', 'default' => 'La finalidad del tratamiento de los datos técnicos es garantizar el correcto funcionamiento y seguridad del sitio web. La base legal es el interés legítimo del responsable (artículo 6.1.f del RGPD).'],
    'text_b019d2968c534e4f' => ['group' => 'Privacidad', 'default' => '4. Plazo de conservación'],
    'text_eeb19871b1ee90fc' => ['group' => 'Privacidad', 'default' => 'Los registros técnicos del servidor se conservan durante el plazo estrictamente necesario para los fines descritos y, en cualquier caso, no más de 12 meses, salvo obligación legal de conservación superior.'],
    'text_be4f5ac046acadcf' => ['group' => 'Privacidad', 'default' => '5. Destinatarios'],
    'text_d6022e000436fc77' => ['group' => 'Privacidad', 'default' => 'No se cederán datos personales a terceros salvo obligación legal. Los datos técnicos pueden ser tratados por el proveedor de alojamiento web del sitio, que actúa como encargado del tratamiento.'],
    'text_1bd56bd31b85e92d' => ['group' => 'Privacidad', 'default' => '6. Derechos del usuario'],
    'text_a442ae75bed6e1cd' => ['group' => 'Privacidad', 'default' => 'Explica cómo las personas usuarias pueden ejercer sus derechos de privacidad y contactar con el responsable.'],
    'text_4aa4c90345d1cc65' => ['group' => 'Privacidad', 'default' => 'Asimismo, tiene derecho a presentar una reclamación ante la'],
    'text_ee696e219150d48a' => ['group' => 'Privacidad', 'default' => 'Agencia Española de Protección de Datos'],
    'text_8ae1d917d6c1ea9c' => ['group' => 'Privacidad', 'default' => 'www.aepd.es'],
    'text_49e605c7193abea0' => ['group' => 'Privacidad', 'default' => ') si considera que el tratamiento de sus datos vulnera la normativa vigente.'],
    'text_d9a7b28cdf8785d9' => ['group' => 'Privacidad', 'default' => '7. Seguridad'],
    'text_baf3aa11631bd30d' => ['group' => 'Privacidad', 'default' => 'El responsable ha adoptado las medidas técnicas y organizativas necesarias para garantizar la seguridad de los datos y evitar su alteración, pérdida, tratamiento o acceso no autorizado, teniendo en cuenta el estado de la tecnología, la naturaleza de los datos almacenados y los riesgos a los que están expuestos.'],
    'text_bd0dfe901546d901' => ['group' => 'Privacidad', 'default' => '8. Modificaciones'],
    'text_e1529cd46482e38e' => ['group' => 'Privacidad', 'default' => 'El responsable se reserva el derecho a modificar la presente política para adaptarla a novedades legislativas o jurisprudenciales. En tales supuestos, anunciará en esta página los cambios introducidos.'],
    'text_914dbdd5fa37fe52' => ['group' => 'Identidad, metadatos y controles', 'default' => 'Política de privacidad · Kookye Cat Gallery'],
    'text_fa322aa36e894213' => ['group' => 'Identidad, metadatos y controles', 'default' => 'Política de Privacidad'],
    'text_49c19ea97b0ee7fb' => ['group' => 'Cookies', 'default' => '1. ¿Qué son las cookies?'],
    'text_a56503b90b90430c' => ['group' => 'Cookies', 'default' => 'Las cookies son pequeños archivos de texto que los sitios web almacenan en el dispositivo del usuario al navegar por ellos. Sirven para reconocer al usuario, recordar preferencias o recopilar información estadística sobre el uso del sitio.'],
    'text_d9f1508e39856918' => ['group' => 'Cookies', 'default' => '2. Cookies utilizadas en este sitio'],
    'text_2872662c369b5663' => ['group' => 'Cookies', 'default' => 'Este sitio web'],
    'text_fdbc92936867cf4c' => ['group' => 'Cookies', 'default' => 'no utiliza cookies propias ni de terceros'],
    'text_d421435680d9ae41' => ['group' => 'Cookies', 'default' => '. No se instalan cookies de análisis, publicidad, seguimiento ni de cualquier otro tipo en el navegador del usuario.'],
    'text_8278cef56c5845b5' => ['group' => 'Cookies', 'default' => 'Tampoco se emplean tecnologías similares como balizas web, píxeles de seguimiento o almacenamiento local del navegador con finalidades de identificación o seguimiento.'],
    'text_080a45aeb99066c1' => ['group' => 'Cookies', 'default' => '3. Servicios de terceros'],
    'text_a4e74f4dc4ac1362' => ['group' => 'Cookies', 'default' => 'El sitio carga tipografías web desde el servicio gratuito'],
    'text_44738161b597e017' => ['group' => 'Cookies', 'default' => 'Google Fonts'],
    'text_3688e598c791f6db' => ['group' => 'Cookies', 'default' => '. Este servicio puede recibir la dirección IP del usuario al solicitar las fuentes. No instala cookies ni recopila otros datos identificativos. Si el usuario desea evitar esta conexión, puede bloquearla mediante extensiones del navegador.'],
    'text_ae27b5d8b9079084' => ['group' => 'Cookies', 'default' => '4. Cómo gestionar las cookies en su navegador'],
    'text_3e1b6617765084b4' => ['group' => 'Cookies', 'default' => 'Aunque este sitio no instale cookies, el usuario puede revisar y configurar el comportamiento de cookies en su navegador en cualquier momento. A continuación se enlazan las instrucciones de los navegadores más comunes:'],
    'text_0e99a87ff0da91ab' => ['group' => 'Cookies', 'default' => 'Google Chrome'],
    'text_acc08972fddf56f3' => ['group' => 'Cookies', 'default' => 'Mozilla Firefox'],
    'text_3035ab6550db87a0' => ['group' => 'Cookies', 'default' => 'Apple Safari'],
    'text_951e7f89043186ca' => ['group' => 'Cookies', 'default' => 'Microsoft Edge'],
    'text_c14529e76b4842fd' => ['group' => 'Cookies', 'default' => '5. Modificaciones'],
    'text_a4c979481ee6a8bf' => ['group' => 'Cookies', 'default' => 'Si en el futuro este sitio incorporase cookies, esta política se actualizará y se solicitará el consentimiento del usuario conforme a la normativa vigente antes de su instalación.'],
    'text_c4a491ae2cd05080' => ['group' => 'Identidad, metadatos y controles', 'default' => 'Política de cookies · Kookye Cat Gallery'],
    'text_e4124618327d933f' => ['group' => 'Identidad, metadatos y controles', 'default' => 'Política de Cookies'],
    'text_d5e9eac00ad801cf' => ['group' => 'Identidad, metadatos y controles', 'default' => 'Compartir'],
    'text_db164690a5469f43' => ['group' => 'Identidad, metadatos y controles', 'default' => 'Copiar enlace'],
    'text_a28cf8674fc26c2a' => ['group' => 'Identidad, metadatos y controles', 'default' => 'Compartir en '],
    'text_0ad82954c86eec7c' => ['group' => 'Identidad, metadatos y controles', 'default' => ' · Kookye Cat Gallery'],
    'text_e4ce7c09d51e3b88' => ['group' => 'Controles e instalación', 'default' => 'Anterior'],
    'text_9bcad734827a849a' => ['group' => 'Controles e instalación', 'default' => 'Página anterior'],
    'text_49683b71c6acf522' => ['group' => 'Controles e instalación', 'default' => 'Siguiente'],
    'text_18b6f81ee66862d8' => ['group' => 'Controles e instalación', 'default' => '
                    Página '],
    'text_9dd6b398421db42f' => ['group' => 'Controles e instalación', 'default' => 'Página siguiente'],
    'text_a266e065c89bb478' => ['group' => 'Controles e instalación', 'default' => '(pincha para ver)'],
    'text_f7dc3bdd83d2aa77' => ['group' => 'Controles e instalación', 'default' => '{count} foto en'],
    'text_fd1e8f465693b0d0' => ['group' => 'Controles e instalación', 'default' => '{count} fotos en'],
    'text_8bcfc94910990d0c' => ['group' => 'Controles e instalación', 'default' => '{count} fotografía en total'],
    'text_84626fb4070cd6bd' => ['group' => 'Controles e instalación', 'default' => '{count} fotografías en total'],
    'text_62f2f3122a240f09' => ['group' => 'Controles e instalación', 'default' => 'Instala Kookye Cat Gallery'],
    'text_15164fffcff855c1' => ['group' => 'Controles e instalación', 'default' => 'En Safari, toca '],
    'text_29b83a6bd90f4dbe' => ['group' => 'Controles e instalación', 'default' => ' y elige '],
    'text_5f2c68d0beff7ca6' => ['group' => 'Controles e instalación', 'default' => 'Añadir a pantalla de inicio'],
    'text_15e4904fbf949256' => ['group' => 'Controles e instalación', 'default' => '. Después podrás abrir la web y el acceso privado como una app.'],
    'text_3f3f7d88e05abb17' => ['group' => 'Controles e instalación', 'default' => 'Entendido'],
    'text_327b07ddd39cddc9' => ['group' => 'Controles e instalación', 'default' => 'Abre el menú '],
    'text_985e6df3e6776ff9' => ['group' => 'Controles e instalación', 'default' => ' de Chrome y selecciona '],
    'text_a2c55ed92eb41069' => ['group' => 'Controles e instalación', 'default' => ' o '],
    'text_5fa52ec5d6bf138e' => ['group' => 'Controles e instalación', 'default' => 'Hay una nueva versión. Se actualizará automáticamente al terminar los cambios de esta página.'],
    'text_5f894de21770ce4f' => ['group' => 'Identidad, metadatos y controles', 'default' => ' — Fotografía de autor por '],
    'text_c7ea52a379d46ca5' => ['group' => 'Identidad, metadatos y controles', 'default' => 'Fotografía de autor por '],
    'text_70241acd5e85d5cc' => ['group' => 'Identidad, metadatos y controles', 'default' => ' — Kookye Cat Gallery'],
    'text_199d79e67ea29a83' => ['group' => 'Identidad, metadatos y controles', 'default' => 'Ver '],
    'text_7be0de9ca7203c46' => ['group' => 'Identidad, metadatos y controles', 'default' => 'Abrir '],
    'text_515a713ceaf4b237' => ['group' => 'Identidad, metadatos y controles', 'default' => '1 foto'],
    'text_47fb7a281b7a00ab' => ['group' => 'Identidad, metadatos y controles', 'default' => '{count} fotos'],
    'text_553c27d45c0c54dc' => ['group' => 'Identidad, metadatos y controles', 'default' => ' de '],
    'text_fefcf69f823e38c3' => ['group' => 'Identidad, metadatos y controles', 'default' => 'Página '],
];
